name: Build and Deploy

on: 
  push:
    branches:
      - main

permissions: 
  contents: write 

jobs:
  build-and-deploy:
    if: "startsWith(github.event.head_commit.message, 'deploy:')"
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v3

      - name: Install dependency 
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build the codebase 
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      
      - name: Deploy the codebase
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist